### ISSUE TITLE
Bug in 2.01

### ISSUE THREAD

**Issue by Ne0-d3gen** [formtools/module-submission_id_manager#2]
When opening the module, the following error (repeated multiple times) is printed at the top of the screen:

> Warning: Illegal string offset 'submission_id' in /home/acutemed/warwickacutemedicine.co.uk/acportfolio/modules/submission_id_manager/index.php on line 67
> 
> Warning: Illegal string offset 'submission_id' in /home/acutemed/warwickacutemedicine.co.uk/acportfolio/modules/submission_id_manager/index.php on line 67
> 
> Warning: Illegal string offset 'submission_id' in /home/acutemed/warwickacutemedicine.co.uk/acportfolio/modules/submission_id_manager/index.php on line 67
> 
> Warning: Illegal string offset 'submission_id' in /home/acutemed/warwickacutemedicine.co.uk/acportfolio/modules/submission_id_manager/index.php on line 67
> 
> Warning: Illegal string offset 'submission_id' in /home/acutemed/warwickacutemedicine.co.uk/acportfolio/modules/submission_id_manager/index.php on line 67
> 
> Warning: Illegal string offset 'submission_id' in /home/acutemed/warwickacutemedicine.co.uk/acportfolio/modules/submission_id_manager/index.php on line 67
> 
> Warning: Illegal string offset 'submission_id' in /home/acutemed/warwickacutemedicine.co.uk/acportfolio/modules/submission_id_manager/index.php on line 67
> 
> Warning: Illegal string offset 'submission_id' in /home/acutemed/warwickacutemedicine.co.uk/acportfolio/modules/submission_id_manager/index.php on line 67
> 
> Warning: Illegal string offset 'submission_id' in /home/acutemed/warwickacutemedicine.co.uk/acportfolio/modules/submission_id_manager/index.php on line 67
> 
> Warning: Illegal string offset 'submission_id' in /home/acutemed/warwickacutemedicine.co.uk/acportfolio/modules/submission_id_manager/index.php on line 67

**Comment by benkeen** [comment]
Thanks @tomheaps, I'll fix this in 2.0.2 tonight.
